sort:
	LC_ALL=C sort allkeys.txt > allkeys-sorted.txt
	LC_ALL=C sort -r allkeys.txt > allkeys-sorted-r.txt
	LC_ALL=C sort -k2 -n allkeys.txt > allkeys-sorted-k2-n.txt
	LC_ALL=C sort -u allkeys.txt > allkeys-sorted-u.txt
	LC_ALL=C sort -k3 -M allkeys.txt > allkeys-sorted-k3-M.txt
	LC_ALL=C sort -b allkeys.txt > allkeys-sorted-b.txt
	# LC_ALL=C sort -c allkeys.txt > allkeys-sorted-c.txt
	LC_ALL=C sort -k4 -h allkeys.txt > allkeys-sorted-k4-h.txt
