cut:
	cat input-01.txt | cut -d: -f1 -s > input-01-cut-d-f1-s.txt
	cat input-01.txt | cut -d: -f2 -s > input-01-cut-d-f2-s.txt
	cat input-01.txt | cut -d: -f3 -s > input-01-cut-d-f3-s.txt
	cat input-01.txt | cut -d: -f4 -s > input-01-cut-d-f4-s.txt
	cat input-01.txt | cut -d: -f5 -s > input-01-cut-d-f5-s.txt
	cat input-01.txt | cut -d: -f1 > input-01-cut-d-f1.txt
	cat input-01.txt | cut -d: -f2 > input-01-cut-d-f2.txt
	cat input-01.txt | cut -d: -f3 > input-01-cut-d-f3.txt
	cat input-01.txt | cut -d: -f4 > input-01-cut-d-f4.txt
	cat input-01.txt | cut -d: -f5 > input-01-cut-d-f5.txt
	cat input-01.txt | cut -d1 -f1 > input-01-cut-d1-f1.txt
	cat input-01.txt | cut -d1 -f2 > input-01-cut-d1-f2.txt