grep:
	man grep > input.txt
	man find >> input.txt
	grep "F.*" input.txt > grep.txt
	grep -A 10 "F.*" input.txt > grep-A.txt
	grep -B 10 "F.*" input.txt > grep-B.txt
	grep -A 2 -B 1 "F.*" input.txt > grep-A2-B1.txt
	grep -C 2 "F.*" input.txt > grep-C.txt
	grep -c "F.*" input.txt > grep-c.txt
	grep -i "F.*" input.txt > grep-i.txt
	grep -v "F.*" input.txt > grep-v.txt
	grep -F "f.*" input.txt > grep-F.txt
	grep -n "f.*" input.txt > grep-n.txt